# Generated by Django 6.0.3 on 2026-03-20 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarborConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('harbor_base_url', models.URLField(default='https://harbor.docklabs.ai', help_text='Base URL for the Harbor instance')),
                ('harbor_api_token', models.CharField(blank=True, help_text='API token for authenticating with Harbor', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harbor_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Harbor Connection',
                'verbose_name_plural': 'Harbor Connections',
            },
        ),
    ]
