# Generated by Django 6.0.3 on 2026-03-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_recipient_notificationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_beta_tester',
            field=models.BooleanField(default=False, help_text='Beta testers can submit feedback directly from within the product.', verbose_name='Beta Tester'),
        ),
    ]
