# Generated by Django 5.2.13 on 2026-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty_core', '0004_notificationpreference_channel_boswell'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='bounty_core_recipie_51a0a7_idx',
            old_name='core_notifi_recipie_f4ed05_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('export', 'Export'), ('view', 'View'), ('login_failed', 'Login Failed'), ('security_event', 'Security Event'), ('archive', 'Archive'), ('unarchive', 'Unarchive')], max_length=25),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='bounty_core_auditlog',
        ),
        migrations.AlterModelTable(
            name='bountyprofile',
            table='bounty_core_bountyprofile',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='bounty_core_notification',
        ),
        migrations.AlterModelTable(
            name='notificationlog',
            table='bounty_core_notificationlog',
        ),
        migrations.AlterModelTable(
            name='notificationpreference',
            table='bounty_core_notificationpreference',
        ),
    ]
