"""Concrete Activity + Watcher models for Bounty.

Sixth product wiring of keel.activity (Phase 1A Week 5 / Phase 1C —
third non-Phase-1A peer, after Lookout and Harbor). Models live in the
``opportunities`` app since TrackedOpportunity is the user-facing record
activity rotates around. The denormalized ``tracked_opportunity`` FK
keeps detail-page feed queries to a single index seek.

Watcher subscribes a user to a TrackedOpportunity. Bounty's existing
``MatchPreference + OpportunityMatch`` (matching app) is a separate
upstream-discovery layer; Watcher is the per-record subscription on the
already-tracked opportunity.
"""
from __future__ import annotations

from django.db import models
from django.db.models import Q

from keel.activity.models import AbstractActivity, AbstractWatcher

from .models import TrackedOpportunity, OpportunityCollaborator


class Activity(AbstractActivity):
    """Per-product Activity row for Bounty opportunities.

    Inherits the abstract base + adds a denormalized ``tracked_opportunity``
    FK so a TrackedOpportunity detail page reads its activity feed via a
    single index seek rather than a GFK round-trip. Backfilled from the
    target GFK in ``save()`` when target IS a TrackedOpportunity.
    """

    tracked_opportunity = models.ForeignKey(
        TrackedOpportunity,
        on_delete=models.CASCADE,
        related_name='activities',
        db_index=True,
        null=True, blank=True,
        help_text='Denormalized FK to TrackedOpportunity for fast detail-page queries. '
                  'Backfilled from target on save when target IS a TrackedOpportunity.',
    )

    class Meta(AbstractActivity.Meta):
        constraints = [
            models.UniqueConstraint(
                fields=['audit_ref'],
                condition=models.Q(audit_ref__isnull=False),
                name='opp_activity_aud_uniq',
            ),
        ]
        indexes = [
            models.Index(
                fields=['target_ct', 'target_id', '-created_at'],
                name='opp_activity_tgt_ix',
            ),
            models.Index(
                fields=['actor', '-created_at'],
                name='opp_activity_act_ix',
            ),
            models.Index(
                fields=['verb', '-created_at'],
                name='opp_activity_verb_ix',
            ),
            models.Index(
                fields=['tracked_opportunity', '-created_at'],
                name='opp_activity_to_ix',
            ),
        ]

    def save(self, *args, **kwargs):
        # Backfill the denormalized tracked_opportunity FK from target when
        # target IS a TrackedOpportunity.
        if self.tracked_opportunity_id is None and self.target_id and self.target_ct_id:
            try:
                if self.target_ct.model == 'trackedopportunity':
                    # target_id is CharField(max_length=64) on AbstractActivity to fit UUIDs.
                    # TrackedOpportunity.id IS a UUID — assign directly.
                    self.tracked_opportunity_id = self.target_id
            except Exception:
                pass
        super().save(*args, **kwargs)

    @classmethod
    def visible_to(cls, user, queryset=None):
        """Visibility: tracked_by + active OpportunityCollaborators see it.

        Bounty has no zone-bridge / external-applicant-portal split (unlike
        Beacon's FOIA zones or Harbor's applicant-vs-staff split), so the
        visibility model is simply: principal driver + any collaborator
        with is_active=True. Stub-tier rows are not generated by Bounty's
        promotion rules in v1.
        """
        qs = queryset if queryset is not None else cls.objects.all()
        if user is None:
            return qs.none()
        if getattr(user, 'is_staff', False) or getattr(user, 'is_superuser', False):
            return qs

        owned_ids = set(
            TrackedOpportunity.objects.filter(tracked_by=user).values_list('id', flat=True)
        )
        owned_ids.update(
            OpportunityCollaborator.objects.filter(user=user, is_active=True)
            .values_list('tracked_opportunity_id', flat=True)
        )

        if not owned_ids:
            return qs.none()

        return qs.filter(
            Q(tracked_opportunity_id__in=owned_ids),
            ~Q(visibility='staff'),
        )

    @classmethod
    def is_visible_to_user(cls, user, activity) -> bool:
        if user is None:
            return False
        if getattr(user, 'is_staff', False) or getattr(user, 'is_superuser', False):
            return True
        if activity.visibility == 'staff':
            return False
        if activity.tracked_opportunity_id is None:
            return False
        if TrackedOpportunity.objects.filter(
            id=activity.tracked_opportunity_id, tracked_by=user,
        ).exists():
            return True
        if OpportunityCollaborator.objects.filter(
            tracked_opportunity_id=activity.tracked_opportunity_id,
            user=user, is_active=True,
        ).exists():
            return True
        return False


class Watcher(AbstractWatcher):
    """Per-product Watcher for Bounty. Same shape as the other peers."""
    class Meta(AbstractWatcher.Meta):
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'target_ct', 'target_id'],
                condition=models.Q(target_ct__isnull=False) & models.Q(target_id__isnull=False),
                name='opp_watcher_uniq',
            ),
        ]
        indexes = [
            models.Index(
                fields=['user', 'target_ct', 'target_id'],
                name='opp_watcher_ut_ix',
            ),
        ]
