# Generated by Django 6.0.3 on 2026-04-03 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_add_search_vectors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedOpportunityStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changes', to=settings.AUTH_USER_MODEL)),
                ('tracked_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='opportunities.trackedopportunity')),
            ],
            options={
                'verbose_name': 'Tracked Opportunity Status History',
                'verbose_name_plural': 'Tracked Opportunity Status Histories',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
    ]
