# Generated by Django 5.2.13 on 2026-04-21 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_trackedopportunitystatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitycollaborator',
            options={'ordering': ['-invited_at'], 'verbose_name': 'Opportunity Collaborator', 'verbose_name_plural': 'Opportunity Collaborators'},
        ),
        migrations.AddField(
            model_name='opportunitycollaborator',
            name='notify_on_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunitycollaborator',
            name='notify_on_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='email',
            field=models.EmailField(blank=True, help_text='Set for external invites.', max_length=254),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='contributor', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunitycollaborator',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Internal user; null for external email invites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackedopportunity',
            name='tracked_by',
            field=models.ForeignKey(blank=True, help_text='Current principal driver. Null when unclaimed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OpportunityAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('claimed', 'Self-claimed'), ('manager_assigned', 'Manager-assigned')], default='claimed', max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('reassigned', 'Reassigned'), ('released', 'Released back to pool')], default='assigned', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Manager who made the assignment; null for self-claims.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_delegated', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_assigned', to=settings.AUTH_USER_MODEL)),
                ('tracked_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='opportunities.trackedopportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Assignment',
                'verbose_name_plural': 'Opportunity Assignments',
                'ordering': ['-claimed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('external', 'External (applicant-visible)'), ('internal', 'Internal (staff-only)')], default='internal', max_length=10)),
                ('source', models.CharField(choices=[('upload', 'Manually uploaded'), ('manifest_signed', 'Signed document returned from Manifest'), ('system', 'System-generated')], default='upload', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('manifest_packet_uuid', models.CharField(blank=True, max_length=64)),
                ('tracked_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='opportunities.trackedopportunity')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity Attachment',
                'verbose_name_plural': 'Opportunity Attachments',
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
        ),
    ]
