# Generated by Django 5.2.13 on 2026-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_backfill_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedopportunity',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('preparing', 'Preparing Application'), ('approved', 'Internally Approved'), ('applied', 'Applied'), ('awarded', 'Awarded'), ('declined', 'Declined')], default='watching', max_length=15),
        ),
    ]
