# Generated by Django 6.0.3 on 2026-03-20 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('funding_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('funding_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match Preference',
                'verbose_name_plural': 'Match Preferences',
            },
        ),
        migrations.CreateModel(
            name='OpportunityMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_score', models.IntegerField(help_text='AI relevance score from 0 to 100')),
                ('explanation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('saved', 'Saved'), ('dismissed', 'Dismissed')], default='new', max_length=10)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], default='', max_length=10)),
                ('feedback_reason', models.CharField(blank=True, choices=[('wrong_focus', 'Wrong focus area'), ('budget_too_large', 'Budget too large'), ('budget_too_small', 'Budget too small'), ('already_aware', 'Already aware of this'), ('not_eligible', 'Not eligible'), ('not_relevant', 'Not relevant to our mission'), ('other', 'Other')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('federal_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='opportunities.federalopportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity Match',
                'verbose_name_plural': 'Opportunity Matches',
                'ordering': ['-relevance_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_oppmatch_user_status')],
                'constraints': [models.UniqueConstraint(fields=('user', 'federal_opportunity'), name='unique_user_federal_match')],
            },
        ),
    ]
