# Generated by Django 6.0.3 on 2026-03-20 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpreference',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords that describe your personal priorities'),
        ),
        migrations.CreateModel(
            name='StatePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='State Matching Profile', help_text='Label for this state-wide preference set', max_length=200)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Keywords that describe state-wide priorities')),
                ('funding_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('funding_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, default='', help_text="Describe the state's overall funding priorities and mission")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_state_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'State Preference',
                'verbose_name_plural': 'State Preferences',
                'ordering': ['-updated_at'],
            },
        ),
    ]
