# Generated by Django 6.0.3 on 2026-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matchpreference_keywords_statepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpreference',
            name='digest_frequency',
            field=models.CharField(choices=[('none', 'No digest'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', help_text='How often to receive a summary of new matches', max_length=10),
        ),
        migrations.AddField(
            model_name='matchpreference',
            name='last_digest_at',
            field=models.DateTimeField(blank=True, help_text='When the last digest email was sent', null=True),
        ),
    ]
